export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENT";
export const SET_INGREDIENTS_SAGA = "SET_INGREDIENTS_SAGA";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_SAGA = "PURCHASE_BURGER_SAGA";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDER_SAGA = "FETCH_ORDER_SAGA";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SAGA = "AUTH_LOGOUT_SAGA";

export const AUTH_CHECK_TIMEOUT_SAGA = "AUTH_CHECK_TIMEOUT_SAGA";

export const AUTH_SAGA = "AUTH_SAGA";
export const AUTH_CHECK_STATE_SAGA = "AUTH_CHECK_STATE_SAGA";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
